### ISSUE TITLE
Attraction mechanics bug

### ISSUE THREAD

**Issue by ckjr** [nginyc/Magnets#13]
![image](https://cloud.githubusercontent.com/assets/1495792/15568808/777393b6-2360-11e6-8344-f5c10e05de60.png)
(Moves one tile to the left)
![image](https://cloud.githubusercontent.com/assets/1495792/15568825/89a694d4-2360-11e6-9055-40ab8342c882.png)

The block is supposed to move to the left, not diagonally left and up.

**Comment by nginyc** [comment]
Should be fixed now, please verify

**Comment by ckjr** [comment]
Verified
