### ISSUE TITLE
Moving Lodestones can clip through player

### ISSUE THREAD

**Issue by ckjr** [nginyc/Magnets#15]
![vid](https://cloud.githubusercontent.com/assets/1495792/15574498/4281c1ee-2380-11e6-9615-65dcd833db92.gif)

**Comment by nginyc** [comment]
Don't really see it as a bug - at tick #1, the player moves down (while graphically it starts moving down, it is already considered to be in the next coordinate), then at tick #2, the block is attracted and starts moving left. There is a slight overlap in the graphics on the way
