### ISSUE TITLE
Ambiguity in attraction order

### ISSUE THREAD

**Issue by nginyc** [nginyc/Magnets#19]
![ambiguity](https://cloud.githubusercontent.com/assets/13707250/15662482/cdbe321e-2723-11e6-9384-af2d2de36f00.gif)

**Comment by ckjr** [comment]
Didn't realize this property. I guess in this situation, choosing either case doesn't make sense, so maybe we don't make them move?

**Comment by nginyc** [comment]
Resolved based on #24
