### ISSUE TITLE
Make cave walls have a lighter colour.

### ISSUE THREAD

**Issue by ckjr** [nginyc/Magnets#23]

**Comment by ckjr** [comment]
@melvinzhang 
![image](https://cloud.githubusercontent.com/assets/1495792/15679047/fc4f79da-2782-11e6-8ad0-dcbffdf0091b.png)

How does this look? I've made it brighter and even added a gradient to it.

**Comment by melvinzhang** [comment]
Yup, looks better! The confusion I had was in determining whether two objects would collide, normally I look at the top face for that and treat the sides and ground as background. With the wall sides being very dark, it started to blend in with the top of the wall.

**Comment by ckjr** [comment]
Alright, thanks for the feedback
