### ISSUE TITLE
Tile that blocks objects but allow player to walk upon.

### ISSUE THREAD

**Issue by ckjr** [nginyc/Magnets#26]

**Comment by ckjr** [comment]
The 3 main uses are to prevent players from accidentally getting a lodestone stuck in the middle of the level, to guide player, and just simply creating more possibilities for levels.

**Comment by nginyc** [comment]
I added the type `Obstructed Floor` a few commits ago - try using it

**Comment by ckjr** [comment]
Done and working. Just need to fix the rendering bugs
