### ISSUE TITLE
Research on possibility of generating dynamic lighting in code

### ISSUE THREAD

**Issue by nginyc** [nginyc/Magnets#32]

**Comment by ckjr** [comment]
Feedback : Can you make it such that the whole level is much darker and then the character can hold a torch or something and it lights up the cave? 

What i think : Currently, I just use a static overlay graphic (which just makes everything a shade darker). I feel like, if possible, we should take this a step further and come up with a system that allows adjustments of the ambiance in levels in some level presets. (I.e. you can state the theme of the level and it will generate accordingly)

A static lighting would be having a screen graphic overlay. 
![image](https://cloud.githubusercontent.com/assets/1495792/15810933/05a6a042-2bd6-11e6-8baf-ed7c24d29508.png)

There are some different types of dynamic lighting we can utilize, but we need to debate on which one is suitable. We may, of course take both. 

1. 
![image](https://cloud.githubusercontent.com/assets/1495792/15810938/14ac4196-2bd6-11e6-9a0b-84785c8cbdd0.png)
Note that we are looking for a less bright and far reaching version of this.

2. If we can use shaders / colouring, it would look something like this. (Check out the site) http://robotloveskitty.tumblr.com/post/33164532086/legend-of-dungeon-dynamic-lighting-on-sprites. It might slow down the game, but who knows. 


A list of points to consider if we are going down this path, 
1. All objects and walls are counted as opaque objects. 
2. There's a possibility of moving light sources (torch held by player)
3. Flickering light sources without player intervention. (Randomly generated animations)

**Comment by ckjr** [comment]
Thinking of wall lighting sources, floor lighting sources (sources that can be covered?)
Also, since in some underground areas, there might be "rays of lights" from above. Those will probably be static and uncoverable light sources, though it might change according to whatever height of the object that is under it.
