### ISSUE TITLE
Flickering magnetic attraction graphic

### ISSUE THREAD

**Issue by ckjr** [nginyc/Magnets#34]
![flicker](https://cloud.githubusercontent.com/assets/1495792/15811476/a2c9177e-2bdb-11e6-948b-56daa60411b3.gif)

(Also wondering if the current game system can support fade in / out. (Since we are considering dynamic lighting)

**Comment by nginyc** [comment]
Should be fixed - please confirm this

**Comment by ckjr** [comment]
Verified
