### ISSUE TITLE
Statistics upon level completion

### ISSUE THREAD

**Issue by ckjr** [nginyc/Magnets#36]
Not all the features mentioned need to be implemented

1. Number of steps walked
2. Total time taken
3. Number of save states used

**Comment by nginyc** [comment]
I feel the statistic for total time taken can be used to back a 3/5 stars rating system for each level. So the best players will need to correctly press the sequence of steps as fast as possible (with the step-queuing mechanic)

**Comment by ckjr** [comment]
Some of the levels are too complicated to determine what is the best sequence of steps possible though. So i suggest that we can set the rating system to use a series of step count benchmarks instead. (i.e.) 10~20, 20~40, 40~80

**Comment by ckjr** [comment]
4. Treasure chests lying around the level and collect them for more score.
