### ISSUE TITLE
Make buttons and doors work

### ISSUE THREAD

**Issue by nginyc** [nginyc/Magnets#4]

**Comment by ckjr** [comment]
All doors of a set will only open after all buttons of the same set are pressed down. 

[Discuss] If the player is standing on the last button, the doors will still open, but will close immediately when the player steps off the button. (However, what if the last button is directly beside the door?)

**Comment by nginyc** [comment]
I can code to allow player movement through the door while he stands on the button to open it

**Comment by ckjr** [comment]
Actually, should that count as a legal movement?

**Comment by ckjr** [comment]
If a door is open (i.e. all buttons pertaining to the same set are pressed down at that point in time), and a block is directly over it, and any of the buttons are released, the door should stay open and remain so until the block-ade is removed.

**Comment by ckjr** [comment]
Also, if that blockade is actually the player, it should behave the same as well.

**Comment by ckjr** [comment]
Should the movements of a block that is attracted by the magnetic source take precedence over the closing of a door?

MBL (M = magnetic source, B = door currently held down by a block to be pushed out of the way, L is the block that can be magnetised)

**Comment by ckjr** [comment]
Just wondering, would doors with their default state open be alright? When all buttons are pressed, then those doors would be closed instead.

**Comment by nginyc** [comment]
Do-able
