### ISSUE TITLE
Fine-tuning rewinding and fast-forwarding

### ISSUE THREAD

**Issue by ckjr** [nginyc/Magnets#51]
Sometimes you want to rewind one step, but you hold the buttons down too long and rewind like 5 steps instead. Solution : Give the player more control. Also, if you are able to rewind, you should be able to fast-forward provided that you do not move the player. Also, maybe hold z, and then press left arrow or right arrow to move between time frames of 1 step. Up arrow and down arrow would be moving between time frames of X steps (x > 1). 

This is with reference with the rewind and fast-forwarding feature in Full Bore, a puzzle platformer game which I really enjoy.

**Comment by nginyc** [comment]
What about just a simple "delayed quick rewind"? Like, similar to how you delete characters while typing when you holding "Backspace" on your keyboard. Holding "Ctrl + Z" will rewind exactly 1 step, and after 1s, it will continuously rewind until you lift "Ctrl + Z"

**Comment by ckjr** [comment]
That works too.
