### ISSUE TITLE
Treasure (blocks that needs to be collected to complete a level)

### ISSUE THREAD

**Issue by ckjr** [nginyc/Magnets#56]
It can't be pushed by the player, only "grabbed" (breaks completely) when the player walks on it. However, it can be pushed if a player pushes against a lodestone in the direction of a treasure, and it can be chained (?). 

All treasure blocks need to be grabbed to exit the level. 

When the player walks to the exit and not all treasures are collected, a cloud bubble pops up above for a few seconds, showing how many treasures that are to be collected before exiting. 

A level can have no treasure blocks.

**Comment by nginyc** [comment]
i think there should be a UI overlay to show the no. of treasure left to collect at all times, not just at the exit

**Comment by ckjr** [comment]
Postponed.

**Comment by ckjr** [comment]
Currently the treasure tile (chest) signifies the end of the level.
