### ISSUE TITLE
Magnet Attraction bug

### ISSUE THREAD

**Issue by ckjr** [nginyc/Magnets#59]
![image](https://cloud.githubusercontent.com/assets/1495792/16906122/3baa7d42-4ce4-11e6-8afd-30ab25a07e48.png)

Pushed the lodestone to the left, rewind, and then pushed it to the left again. The magnetic attraction arrows will remain on the lodestone after that.

**Comment by ckjr** [comment]
![image](https://cloud.githubusercontent.com/assets/1495792/16909387/00bdb4a8-4d05-11e6-8e92-bc86ddb80d78.png)
![image](https://cloud.githubusercontent.com/assets/1495792/16909394/0aec97be-4d05-11e6-8089-0de5f00e5cb0.png)

The magnetic attraction light remains on.

![image](https://cloud.githubusercontent.com/assets/1495792/16909404/26f24134-4d05-11e6-9c5b-28e1d65475ad.png)

After rewinding to the start, now it does not appear.

**Comment by nginyc** [comment]
Confirmed by conan
