### ISSUE TITLE
Bigger blocks not rendered when they are at the far right corner of the screen

### ISSUE THREAD

**Issue by ckjr** [nginyc/Magnets#6]
See Wrong Gear.tmx for reference. From the starting point, move to the right and then up down to see it in action.

**Comment by ckjr** [comment]
Also, the blocks at the lower half of the level are not rendered at all.

**Comment by nginyc** [comment]
This should be fixed already - please verify

**Comment by ckjr** [comment]
Looks fine so far. Any further graphical glitches will be submitted as a new issue.
