### ISSUE TITLE
Lighting Rendering bug (with exits)

### ISSUE THREAD

**Issue by ckjr** [nginyc/Magnets#60]
![image](https://cloud.githubusercontent.com/assets/1495792/16909282/4cd405d2-4d04-11e6-92f9-861065a70c18.png)
![image](https://cloud.githubusercontent.com/assets/1495792/16909293/6a4f1d36-4d04-11e6-898a-5ec4a3dd684b.png)

Sometimes the exit lighting renders behind exits. Not sure about the other objects.

**Comment by nginyc** [comment]
This is solvable by changing the property `Render Depth` of `Light Rays Above` tile in tilset.tsx to a number higher than the `Render Depth` of any other tiles that could block it (eg. 5), because the way i render lighting (only lighting) is by render depth, *regardless* of row

**Comment by ckjr** [comment]
Fixed
