### ISSUE TITLE
Pushing mechanic bug

### ISSUE THREAD

**Issue by ckjr** [nginyc/Magnets#9]
![image](https://cloud.githubusercontent.com/assets/1495792/15535000/10602d82-229e-11e6-9bba-d4044017d2b0.png)

In the level, Triparte.tmx, the 2x1 block turns into a 1x1 block and then disappears off screen completely when pushed. This happens when trying to push it to the left.

**Comment by nginyc** [comment]
This should be fixed - can go verify

**Comment by ckjr** [comment]
Verified
